# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "scorm_cloud"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aura Software", "Ken Richard"]
  s.date = "2012-11-08"
  s.description = "Rustici Scorm Cloud Web Service API Wrapper"
  s.email = "support@aura-software.com"
  s.files = [
    "Gemfile",
    "Rakefile",
    "VERSION",
    "features/api_bugs.feature",
    "features/course_service.feature",
    "features/debug_service.feature",
    "features/registration_service.feature",
    "features/step_definitions/scorm_cloud_steps.rb",
    "features/support/env.rb",
    "features/upload_service.feature",
    "lib/scorm_cloud.rb",
    "lib/scorm_cloud/base.rb",
    "lib/scorm_cloud/base_object.rb",
    "lib/scorm_cloud/base_service.rb",
    "lib/scorm_cloud/connection.rb",
    "lib/scorm_cloud/course.rb",
    "lib/scorm_cloud/course_service.rb",
    "lib/scorm_cloud/debug_service.rb",
    "lib/scorm_cloud/dispatch_service.rb",
    "lib/scorm_cloud/export_service.rb",
    "lib/scorm_cloud/railtie.rb",
    "lib/scorm_cloud/registration.rb",
    "lib/scorm_cloud/registration_service.rb",
    "lib/scorm_cloud/reporting_service.rb",
    "lib/scorm_cloud/scorm_rails_helpers.rb",
    "lib/scorm_cloud/tagging_service.rb",
    "lib/scorm_cloud/upload_service.rb",
    "lib/scorm_cloud/version.rb",
    "readme.textile",
    "scorm_cloud.gemspec",
    "spec/apikey_template.rb",
    "spec/course_service_spec.rb",
    "spec/debug_service_spec.rb",
    "spec/dispatch_service_spec.rb",
    "spec/export_service_spec.rb",
    "spec/registration_service_spec.rb",
    "spec/reporting_service_spec.rb",
    "spec/small_scorm_package.zip",
    "spec/spec_helper.rb",
    "spec/tagging_service_spec.rb",
    "spec/upload_service_spec.rb"
  ]
  s.homepage = "http://github.com/redhatcat/scorm-cloud"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Rustici Scorm Cloud Web Service API Wrapper"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<multipart-post>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
    else
      s.add_dependency(%q<multipart-post>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
    end
  else
    s.add_dependency(%q<multipart-post>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
  end
end

